In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
import seaborn as sns

In [ ]:
df = pd.read_csv('Advertising.csv')

In [ ]:
df.head()

,TV,radio,newspaper,sales
0,230.1,37.8,69.2,22.1
1,44.5,39.3,45.1,10.4
2,17.2,45.9,69.3,9.3
3,151.5,41.3,58.5,18.5
4,180.8,10.8,58.4,12.9


In [ ]:
X = df.drop('sales', axis = 1)

In [ ]:
y = df['sales']

In [ ]:
from sklearn.preprocessing import PolynomialFeatures

In [ ]:
polynomial_converter = PolynomialFeatures(degree = 2, include_bias = False)

In [ ]:
polynomial_converter.fit(X)

PolynomialFeatures(include_bias=False)

In [ ]:
polynomial_converter.transform(X)

array([[ 230.1 ,   37.8 ,   69.2 , ..., 1428.84, 2615.76, 4788.64],
       [  44.5 ,   39.3 ,   45.1 , ..., 1544.49, 1772.43, 2034.01],
       [  17.2 ,   45.9 ,   69.3 , ..., 2106.81, 3180.87, 4802.49],
       ...,
       [ 177.  ,    9.3 ,    6.4 , ...,   86.49,   59.52,   40.96],
       [ 283.6 ,   42.  ,   66.2 , ..., 1764.  , 2780.4 , 4382.44],
       [ 232.1 ,    8.6 ,    8.7 , ...,   73.96,   74.82,   75.69]])

In [ ]:
poly_features =polynomial_converter.fit_transform(X)

In [ ]:
poly_features[0]

array([2.301000e+02, 3.780000e+01, 6.920000e+01, 5.294601e+04,
       8.697780e+03, 1.592292e+04, 1.428840e+03, 2.615760e+03,
       4.788640e+03])

In [ ]:
poly_features[0][:3]

array([230.1,  37.8,  69.2])

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(poly_features, y, test_size = 0.3, random_state = 101)

In [ ]:
from sklearn.linear_model import LinearRegression

In [ ]:
model = LinearRegression()

In [ ]:
model.fit(X_train, y_train)

LinearRegression()

In [ ]:
test_predictions = model.predict(X_test)

In [ ]:
model.coef_

array([ 5.17095811e-02,  1.30848864e-02,  1.20000085e-02, -1.10892474e-04,
        1.14212673e-03, -5.24100082e-05,  3.34919737e-05,  1.46380310e-04,
       -3.04715806e-05])

In [ ]:
poly_features[0]

array([2.301000e+02, 3.780000e+01, 6.920000e+01, 5.294601e+04,
       8.697780e+03, 1.592292e+04, 1.428840e+03, 2.615760e+03,
       4.788640e+03])

Ridge(L2) Regularization

In [ ]:
from sklearn.linear_model import Ridge

In [ ]:
ridge_model = Ridge(alpha = 10)

In [ ]:
ridge_model.fit(X_train, y_train)

Ridge(alpha=10)

In [ ]:
test_predictions = ridge_model.predict(X_test)

In [ ]:
from sklearn.metrics import mean_absolute_error, mean_squared_error

In [ ]:
MAE = mean_absolute_error(y_test, test_predictions)

In [ ]:
MAE

0.48964179818294795

In [ ]:
RMSE = np.sqrt(mean_squared_error(y_test, test_predictions))

In [ ]:
RMSE

np.float64(0.6646503354139192)

In [ ]:
from sklearn.linear_model import RidgeCV

In [ ]:
ridge_cv_model = RidgeCV(alphas= (0.1, 1.0, 10.0), scoring = 'neg_mean_absolute_error')

In [ ]:
ridge_cv_model.fit(X_train, y_train)

RidgeCV(scoring='neg_mean_absolute_error')

In [ ]:
ridge_cv_model.alpha_

np.float64(10.0)

In [ ]:
from sklearn.metrics import get_scorer_names

# To see the available scorers:
# print(get_scorer_names())

In [ ]:
get_scorer_names

<function sklearn.metrics._scorer.get_scorer_names()>

In [ ]:
test_predictions = ridge_cv_model.predict(X_test)

In [ ]:
MAE = mean_absolute_error(y_test, test_predictions)

In [ ]:
RMSE = np.sqrt(mean_squared_error(y_test, test_predictions))

In [ ]:
MAE

0.4896419415414565

In [ ]:
RMSE

np.float64(0.6646506280444593)

In [ ]:
ridge_cv_model.coef_

array([ 5.17010794e-02,  1.30078679e-02,  1.19698970e-02, -1.10875162e-04,
        1.14221550e-03, -5.23753500e-05,  3.45356168e-05,  1.46748456e-04,
       -3.03304244e-05])

In [ ]:
ridge_cv_model.

<function sklearn.utils._metadata_requests.RequestMethod.__get__.<locals>.func(self: sklearn.linear_model._ridge.RidgeCV, *, sample_weight: Union[bool, NoneType, str] = '$UNCHANGED$') -> sklearn.linear_model._ridge.RidgeCV>

LASSO (L1) regularization (Least absolute shrinkage and selection operator)

In [ ]:
from sklearn.linear_model import LassoCV

In [ ]:
lasso_cv_model = LassoCV(eps = 0.1, n_alphas = 1000, cv = 5)

In [ ]:
lasso_cv_model.fit(X_train, y_train)

LassoCV(cv=5, eps=0.1, n_alphas=1000)

In [ ]:
lasso_cv_model.alpha_

np.float64(9331.637903102042)

In [ ]:
test_predictions = lasso_cv_model.predict(X_test)

In [ ]:
MAE = mean_absolute_error(y_test, test_predictions)

In [ ]:
RMSE = np.sqrt(mean_squared_error(y_test, test_predictions))

In [ ]:
lasso_cv_model.coef_

array([0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 1.28232569e-04,
       1.91250496e-05, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00])

In [ ]:
from sklearn.linear_model import ElasticNetCV

In [ ]:
elastic_model = ElasticNetCV(l1_ratio =[.1, .5, .7, .9, .95, .99, 1], eps = 0.001, n_alphas = 100, max_iter = 1000000)

In [ ]:
elastic_model.fit(X_train, y_train)

ElasticNetCV(l1_ratio=[0.1, 0.5, 0.7, 0.9, 0.95, 0.99, 1], max_iter=1000000)

In [ ]:
elastic_model.l1_ratio_

np.float64(1.0)

In [ ]:
elastic_model.alpha_

np.float64(163.0730225425898)

In [ ]:
test_predictions = elastic_model.predict(X_test)

In [ ]:
MAE = mean_absolute_error(y_test, test_predictions)

In [ ]:
RMSE = np.sqrt(mean_squared_error(y_test, test_predictions))

In [ ]:
MAE

0.8095871425145572

In [ ]:
RMSE

np.float64(1.2151556695813133)